// <auto-generated />
using System;
using Balsm.CareDirectory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.CareDirectory.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(CareDirectoryDbContext))]
    [Migration("20260913193407_AddMapPackArtifact")]
    partial class AddMapPackArtifact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.CareDirectory.Domain.Entities.CarePlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AddressAr")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_ar");

                    b.Property<string>("AddressArNorm")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_ar_norm");

                    b.Property<string>("AddressEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_en");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Hours")
                        .HasColumnType("TEXT")
                        .HasColumnName("hours");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL")
                        .HasColumnName("lng");

                    b.Property<string>("NameAr")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameArNorm")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_ar_norm");

                    b.Property<string>("NameEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_en");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AddressArNorm");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("NameArNorm");

                    b.HasIndex("CountryCode", "Type");

                    b.ToTable("care_place", "public");
                });

            modelBuilder.Entity("Balsm.CareDirectory.Domain.Entities.MapPackArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("East")
                        .HasColumnType("REAL")
                        .HasColumnName("east");

                    b.Property<string>("GovernorateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("governorate_id");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name_en");

                    b.Property<double>("North")
                        .HasColumnType("REAL")
                        .HasColumnName("north");

                    b.Property<int?>("PlaceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("place_count");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<double>("South")
                        .HasColumnType("REAL")
                        .HasColumnName("south");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.Property<double>("West")
                        .HasColumnType("REAL")
                        .HasColumnName("west");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId", "Kind")
                        .IsUnique();

                    b.ToTable("map_pack_artifact", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
