// <auto-generated />
using System;
using Balsm.Auth.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.Auth.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260706162021_InitialAuthSchema")]
    partial class InitialAuthSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.Auth.Domain.Entities.AccountLockout", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT")
                        .HasColumnName("identifier");

                    b.Property<short>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((short)0)
                        .HasColumnName("failed_attempts");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("identifier_type");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until");

                    b.Property<DateTime>("RollingWindowStartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("rolling_window_started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Identifier");

                    b.ToTable("account_lockout", "public", t =>
                        {
                            t.HasCheckConstraint("CK_account_lockout_identifier_type", "identifier_type IN ('email','apple_sub','google_sub','handle')");
                        });
                });

            modelBuilder.Entity("Balsm.Auth.Domain.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("email_confirmed_at");

                    b.Property<string>("EmailNormalized")
                        .HasColumnType("citext")
                        .HasColumnName("email_normalized");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("user_identities", "public", t =>
                        {
                            t.HasCheckConstraint("CK_user_identities_provider", "provider IN ('email','google','apple')");
                        });
                });

            modelBuilder.Entity("Balsm.Auth.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("user_refresh_token", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
