// <auto-generated />
using System;
using Balsm.CareDirectory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balsm.CareDirectory.Infrastructure.Migrations
{
    [DbContext(typeof(CareDirectoryDbContext))]
    [Migration("20260729142605_InitialCareDirectorySchema")]
    partial class InitialCareDirectorySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balsm.CareDirectory.Domain.Entities.CarePlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_ar");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_en");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hours");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Type");

                    b.ToTable("care_place", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            AddressAr = "شارع قصر العيني، القاهرة",
                            AddressEn = "Al-Kasr Al-Aini St, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "24/7",
                            Lat = 29.976500000000001,
                            Lng = 31.235700000000001,
                            NameAr = "مستشفى قصر العيني",
                            NameEn = "Qasr Al-Aini Hospital",
                            Phone = "+20 2 2365 1234",
                            Rating = 4.2000000000000002,
                            Type = "hospital"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            AddressAr = "الزمالك، القاهرة",
                            AddressEn = "Zamalek, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "9am – 5pm",
                            Lat = 30.061399999999999,
                            Lng = 31.2197,
                            NameAr = "عيادة د. سارة كمال",
                            NameEn = "Dr. Sara Kamal Clinic",
                            Phone = "+20 10 9876 5432",
                            Rating = 4.9000000000000004,
                            Type = "clinic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            AddressAr = "ميدان التحرير، القاهرة",
                            AddressEn = "Tahrir Sq, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "8am – 12am",
                            Lat = 30.0444,
                            Lng = 31.235700000000001,
                            NameAr = "صيدلية العزبي",
                            NameEn = "El-Ezaby Pharmacy",
                            Phone = "+20 2 2574 3210",
                            Rating = 4.5,
                            Type = "pharmacy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            AddressAr = "جاردن سيتي، القاهرة",
                            AddressEn = "Garden City, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "7am – 9pm",
                            Lat = 30.034500000000001,
                            Lng = 31.231000000000002,
                            NameAr = "مختبر ألفا سكان",
                            NameEn = "Alfa Scan Lab",
                            Phone = "+20 2 2795 6789",
                            Rating = 4.7000000000000002,
                            Type = "lab"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            AddressAr = "المهندسين، الجيزة",
                            AddressEn = "Mohandiseen, Giza",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "8am – 10pm",
                            Lat = 30.056100000000001,
                            Lng = 31.200299999999999,
                            NameAr = "مركز القاهرة للأشعة",
                            NameEn = "Cairo Radiology Center",
                            Phone = "+20 2 3304 5678",
                            Rating = 4.5999999999999996,
                            Type = "scan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            AddressAr = "الدقي، الجيزة",
                            AddressEn = "Dokki, Giza",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "9am – 8pm",
                            Lat = 30.038399999999999,
                            Lng = 31.2119,
                            NameAr = "الحياة للمستلزمات الطبية",
                            NameEn = "Al-Hayat Medical Supplies",
                            Phone = "+20 2 3761 2345",
                            Rating = 4.2999999999999998,
                            Type = "store"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            AddressAr = "العجوزة، الجيزة",
                            AddressEn = "Agouza, Giza",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "24/7",
                            Lat = 30.056999999999999,
                            Lng = 31.210999999999999,
                            NameAr = "صيدلية سيف",
                            NameEn = "Seif Pharmacy",
                            Phone = "+20 2 3748 9012",
                            Rating = 4.4000000000000004,
                            Type = "pharmacy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            AddressAr = "مدينة نصر، القاهرة",
                            AddressEn = "Nasr City, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "10am – 6pm",
                            Lat = 30.051100000000002,
                            Lng = 31.365600000000001,
                            NameAr = "عيادة كابيتال",
                            NameEn = "Capital Clinic",
                            Phone = "+20 2 2402 3456",
                            Rating = 4.0999999999999996,
                            Type = "clinic"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            AddressAr = "عين شمس، القاهرة",
                            AddressEn = "Ain Shams, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "24/7",
                            Lat = 30.129999999999999,
                            Lng = 31.283000000000001,
                            NameAr = "مستشفى عين شمس التخصصي",
                            NameEn = "Ain Shams Specialized Hospital",
                            Phone = "+20 2 2601 7890",
                            Rating = 4.2999999999999998,
                            Type = "hospital"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            AddressAr = "مصر الجديدة، القاهرة",
                            AddressEn = "Heliopolis, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "7am – 11pm",
                            Lat = 30.088000000000001,
                            Lng = 31.321999999999999,
                            NameAr = "كايرو لاب",
                            NameEn = "Cairo Lab",
                            Phone = "+20 2 2690 1234",
                            Rating = 4.7999999999999998,
                            Type = "lab"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            AddressAr = "المهندسين، الجيزة",
                            AddressEn = "Mohandeseen, Giza",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "8am – 8pm",
                            Lat = 30.055499999999999,
                            Lng = 31.200500000000002,
                            NameAr = "مركز الهلال الأخضر للأشعة",
                            NameEn = "Green Crescent Scan Center",
                            Phone = "+20 2 3303 1234",
                            Rating = 4.5,
                            Type = "scan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            AddressAr = "الزمالك، القاهرة",
                            AddressEn = "Zamalek, Cairo",
                            CountryCode = "EG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hours = "9am – 7pm",
                            Lat = 30.062000000000001,
                            Lng = 31.219999999999999,
                            NameAr = "ميدلاين للمستلزمات الطبية",
                            NameEn = "MedLine Medical Supplies",
                            Phone = "+20 2 2736 5678",
                            Rating = 4.2000000000000002,
                            Type = "store"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
