// <auto-generated />
using System;
using Balsm.CareTeam.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balsm.CareTeam.Infrastructure.Migrations
{
    [DbContext(typeof(CareTeamDbContext))]
    [Migration("20260923213807_InitialCareTeamSchema")]
    partial class InitialCareTeamSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balsm.CareTeam.Domain.Entities.CareProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Address")
                        .HasColumnType("bytea")
                        .HasColumnName("address_ct");

                    b.Property<byte[]>("Clinic")
                        .HasColumnType("bytea")
                        .HasColumnName("clinic_ct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<byte[]>("Email")
                        .HasColumnType("bytea")
                        .HasColumnName("email_ct");

                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_profile_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<byte[]>("MapUrl")
                        .HasColumnType("bytea")
                        .HasColumnName("map_url_ct");

                    b.Property<byte[]>("Name")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("name_ct");

                    b.Property<byte[]>("Notes")
                        .HasColumnType("bytea")
                        .HasColumnName("notes_ct");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_ct");

                    b.Property<byte[]>("Phone2")
                        .HasColumnType("bytea")
                        .HasColumnName("phone2_ct");

                    b.Property<byte[]>("Specialty")
                        .HasColumnType("bytea")
                        .HasColumnName("specialty_ct");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "HealthProfileId", "UpdatedAt");

                    b.ToTable("care_provider", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
