// <auto-generated />
using System;
using Balsm.Geofence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.Geofence.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(GeofenceDbContext))]
    [Migration("20260706162057_InitialGeofenceSchema")]
    partial class InitialGeofenceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.Geofence.Domain.Entities.DeniedCountryBlocklist", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("CountryCode");

                    b.ToTable("denied_country_blocklist", "public", t =>
                        {
                            t.HasCheckConstraint("CK_denied_country_blocklist_source", "source IN ('ofac','apple_denied','google_denied','manual')");
                        });

                    b.HasData(
                        new
                        {
                            CountryCode = "CU",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(4706),
                            Source = "ofac"
                        },
                        new
                        {
                            CountryCode = "IR",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(5249),
                            Source = "ofac"
                        },
                        new
                        {
                            CountryCode = "KP",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(5253),
                            Source = "ofac"
                        },
                        new
                        {
                            CountryCode = "SY",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(5254),
                            Source = "ofac"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
