// <auto-generated />
using System;
using Balsm.Disclosure.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balsm.Disclosure.Infrastructure.Migrations
{
    [DbContext(typeof(DisclosureDbContext))]
    [Migration("20260705222858_InitialDisclosureSchema")]
    partial class InitialDisclosureSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balsm.Disclosure.Domain.Entities.DisclosureAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CountryCodeAtAccept")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code_at_accept");

                    b.Property<string>("DisclosureId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("disclosure_id");

                    b.Property<string>("PreferredLanguageAtAccept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_language_at_accept");

                    b.Property<string>("SupervisoryAuthorityNameAtAccept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supervisory_authority_name_at_accept");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DisclosureId", "Version")
                        .IsUnique();

                    b.ToTable("disclosure_acceptance", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
