// <auto-generated />
using System;
using Balsm.EmergencyQr.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.EmergencyQr.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(EmergencyQrDbContext))]
    [Migration("20260915160800_ProfileQrV2")]
    partial class ProfileQrV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.EmergencyQr.Domain.Entities.EmergencyQrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("jti");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("ProfileEtag")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_etag");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ttl_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("type")
                        .HasDefaultValue("profile");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("emergency_qr_token", "public", t =>
                        {
                            t.HasCheckConstraint("CK_emergency_qr_token_ttl", "ttl_seconds IN (0, 3600, 21600, 86400, 604800)");
                        });
                });

            modelBuilder.Entity("Balsm.EmergencyQr.Domain.Entities.QrScanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientClass")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_class");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("TEXT")
                        .HasColumnName("token_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ResolvedAt");

                    b.ToTable("qr_scan_record", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
