// <auto-generated />
using System;
using Balsm.Geofence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balsm.Geofence.Infrastructure.Migrations
{
    [DbContext(typeof(GeofenceDbContext))]
    partial class GeofenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balsm.Geofence.Domain.Entities.DeniedCountryBlocklist", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("CountryCode");

                    b.ToTable("denied_country_blocklist", "public", t =>
                        {
                            t.HasCheckConstraint("CK_denied_country_blocklist_source", "source IN ('ofac','apple_denied','google_denied','manual')");
                        });

                    b.HasData(
                        new
                        {
                            CountryCode = "CU",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(4706),
                            Source = "ofac"
                        },
                        new
                        {
                            CountryCode = "IR",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(5249),
                            Source = "ofac"
                        },
                        new
                        {
                            CountryCode = "KP",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(5253),
                            Source = "ofac"
                        },
                        new
                        {
                            CountryCode = "SY",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 39, 875, DateTimeKind.Utc).AddTicks(5254),
                            Source = "ofac"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
