// <auto-generated />
using System;
using Balsm.CareTeam.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.CareTeam.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(CareTeamDbContext))]
    partial class CareTeamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.CareTeam.Domain.Entities.CareProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<byte[]>("Address")
                        .HasColumnType("bytea")
                        .HasColumnName("address_ct");

                    b.Property<byte[]>("Clinic")
                        .HasColumnType("bytea")
                        .HasColumnName("clinic_ct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<byte[]>("Email")
                        .HasColumnType("bytea")
                        .HasColumnName("email_ct");

                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("health_profile_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<byte[]>("MapUrl")
                        .HasColumnType("bytea")
                        .HasColumnName("map_url_ct");

                    b.Property<byte[]>("Name")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("name_ct");

                    b.Property<byte[]>("Notes")
                        .HasColumnType("bytea")
                        .HasColumnName("notes_ct");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_ct");

                    b.Property<byte[]>("Phone2")
                        .HasColumnType("bytea")
                        .HasColumnName("phone2_ct");

                    b.Property<byte[]>("Specialty")
                        .HasColumnType("bytea")
                        .HasColumnName("specialty_ct");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "HealthProfileId", "UpdatedAt");

                    b.ToTable("care_provider", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
