#!/usr/bin/env python3
"""Generate and validate every config key list from config/manifest.yaml.

  --write   regenerate .env.staging.example and config/keys.generated.tsv
  --check   fail if the manifest disagrees with the code or with docker-compose.yml

The manifest is the single source of truth. Nothing else may hand-maintain a key
list; this script is what keeps the derived files honest.
"""
import argparse, pathlib, re, subprocess, sys
import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "config" / "manifest.yaml"
EXAMPLE = ROOT / ".env.staging.example"
TSV = ROOT / "config" / "keys.generated.tsv"
COMPOSE = ROOT / "docker-compose.yml"

# Classes that belong in the deployed env file.
ENV_FILE_CLASSES = {"infra", "app", "flat"}


def load():
    return yaml.safe_load(MANIFEST.read_text())["keys"]


def env_name(k):
    """Env var name for a key: app keys nest with '__', others are literal."""
    if "env" in k:
        return k["env"]
    return k["key"].replace(":", "__")


def in_env_file(k):
    return k["class"] in ENV_FILE_CLASSES and not k.get("forbidden_in")


def render_example(keys):
    out = [
        "# GENERATED by scripts/config-sync.py from config/manifest.yaml — do not edit.",
        "# Regenerate: python3 scripts/config-sync.py --write",
        "#",
        "# Secrets are blank here on purpose. On a fresh deploy bootstrap-staging-env.sh",
        "# mints the generated ones; the rest arrive from GitHub secrets at deploy time.",
        "",
    ]
    for group, title in (("infra", "docker compose only"),
                         ("app", "application config (.NET keys, ':' -> '__')"),
                         ("flat", "literal env names read by the app")):
        section = [k for k in keys if k["class"] == group and in_env_file(k)]
        if not section:
            continue
        out.append(f"# ---- {title} " + "-" * max(0, 62 - len(title)))
        for k in section:
            if k.get("note"):
                for line in re.findall(r".{1,74}(?:\s|$)", " ".join(k["note"].split())):
                    out.append(f"# {line.strip()}")
            val = "" if k.get("secret") else (k.get("default") or "")
            out.append(f"{env_name(k)}={val}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_tsv(keys):
    """Machine-readable key list so shell scripts never parse YAML."""
    rows = ["# GENERATED by scripts/config-sync.py — do not edit.",
            "# name\tclass\tsecret\tgenerate\tdefault"]
    for k in keys:
        if not in_env_file(k):
            continue
        rows.append("\t".join([
            env_name(k), k["class"],
            "1" if k.get("secret") else "0",
            k.get("generate", ""),
            str(k.get("default", "")),
        ]))
    return "\n".join(rows) + "\n"


KEY_PATTERNS = [
    re.compile(r'(?:configuration|Configuration|_config|config)\s*\[\s*"([^"]+)"'),
    re.compile(r'GetValue<[^>]+>\(\s*"([^"]+)"'),
    re.compile(r'GetSection\(\s*"([^"]+)"'),
]


def code_keys():
    found = set()
    for p in (ROOT / "src").rglob("*.cs"):
        if any(part in ("bin", "obj") for part in p.parts):
            continue
        txt = p.read_text(errors="ignore")
        for rx in KEY_PATTERNS:
            found.update(rx.findall(txt))
    return found


def compose_env_vars():
    txt = COMPOSE.read_text()
    return set(re.findall(r"\$\{([A-Z0-9_]+)", txt))


def check(keys):
    declared_dotnet = {k["key"] for k in keys if "key" in k}
    declared_env = {env_name(k) for k in keys}
    problems = []

    undeclared = sorted(k for k in code_keys() if k not in declared_dotnet and k not in declared_env)
    for k in undeclared:
        problems.append(f"code reads '{k}' but config/manifest.yaml does not declare it")

    for v in sorted(compose_env_vars() - declared_env):
        problems.append(f"docker-compose.yml interpolates ${{{v}}} but the manifest does not declare it")

    for path, rendered in ((EXAMPLE, render_example(keys)), (TSV, render_tsv(keys))):
        if not path.exists():
            problems.append(f"{path.relative_to(ROOT)} is missing — run --write")
        elif path.read_text() != rendered:
            problems.append(f"{path.relative_to(ROOT)} is stale — run --write")

    for k in keys:
        if k.get("forbidden_in") and not k.get("secret") and k["class"] == "app":
            pass  # forbidden non-secrets are fine to appear with a default
    return problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    keys = load()

    if a.write:
        EXAMPLE.write_text(render_example(keys))
        TSV.write_text(render_tsv(keys))
        print(f"wrote {EXAMPLE.relative_to(ROOT)} and {TSV.relative_to(ROOT)}")
        return 0

    if a.check:
        problems = check(keys)
        if problems:
            print("config drift:", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            return 1
        print(f"config OK — {len(keys)} keys declared, derived files current")
        return 0

    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
