// <auto-generated />
using System;
using System.Net;
using Balsm.Account.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balsm.Account.Infrastructure.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260729120000_AddAccountNameFields")]
    partial class AddAccountNameFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balsm.Account.Domain.Entities.ReservedHandleBlocklist", b =>
                {
                    b.Property<string>("HandleNormalized")
                        .HasColumnType("citext")
                        .HasColumnName("handle_normalized");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("system")
                        .HasColumnName("added_by");

                    b.HasKey("HandleNormalized");

                    b.ToTable("reserved_handle_blocklist", "public");

                    b.HasData(
                        new
                        {
                            HandleNormalized = "admin",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(7629),
                            AddedBy = "system"
                        },
                        new
                        {
                            HandleNormalized = "balsm",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(8257),
                            AddedBy = "system"
                        },
                        new
                        {
                            HandleNormalized = "support",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(8261),
                            AddedBy = "system"
                        },
                        new
                        {
                            HandleNormalized = "api",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(8262),
                            AddedBy = "system"
                        },
                        new
                        {
                            HandleNormalized = "help",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(8263),
                            AddedBy = "system"
                        },
                        new
                        {
                            HandleNormalized = "null",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(8264),
                            AddedBy = "system"
                        },
                        new
                        {
                            HandleNormalized = "health",
                            AddedAt = new DateTime(2026, 7, 5, 22, 28, 28, 9, DateTimeKind.Utc).AddTicks(8268),
                            AddedBy = "system"
                        });
                });

            modelBuilder.Entity("Balsm.Account.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("DateOfBirthCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("date_of_birth_ciphertext");

                    b.Property<DateTime?>("DeletionConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_confirmed_at");

                    b.Property<DateTime?>("DeletionGraceUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_grace_until");

                    b.Property<string>("DeletionState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("deletion_state");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<string>("Handle")
                        .HasColumnType("citext")
                        .HasColumnName("handle");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_name");

                    b.Property<byte[]>("NationalIdCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("national_id_ciphertext");

                    b.Property<string>("Nationality")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nationality");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasFilter("handle IS NOT NULL");

                    b.ToTable("user_account", "public", t =>
                        {
                            t.HasCheckConstraint("CK_user_account_deletion_state", "deletion_state IN ('ACTIVE','DELETION_REQUESTED','DELETION_CANCELLED')");
                        });
                });

            modelBuilder.Entity("Balsm.Account.Domain.Entities.UserAccountAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("ReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at")
                        .HasDefaultValueSql("now()");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId", "ReadAt");

                    b.ToTable("user_account_audit_log", "public");
                });

            modelBuilder.Entity("Balsm.Account.Domain.Entities.UsernameReservation", b =>
                {
                    b.Property<string>("HandleNormalized")
                        .HasColumnType("citext")
                        .HasColumnName("handle_normalized");

                    b.Property<DateTime>("ClaimedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("HandleNormalized");

                    b.ToTable("username_reservation", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
