// <auto-generated />
using System;
using Balsm.Deletion.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.Deletion.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(DeletionDbContext))]
    [Migration("20260706162040_InitialDeletionSchema")]
    partial class InitialDeletionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.Deletion.Domain.Entities.DeletionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppleRevokeStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("apple_revoke_status");

                    b.Property<string>("CountryCodeAtDeletion")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code_at_deletion");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("PurgeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("purge_at");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason_code");

                    b.Property<string>("UserIdHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id_hash");

                    b.HasKey("Id");

                    b.ToTable("deletion_log", "public", t =>
                        {
                            t.HasCheckConstraint("CK_deletion_log_apple_revoke_status", "apple_revoke_status IS NULL OR apple_revoke_status IN ('not_applicable','succeeded','failed_final','failed_retrying')");

                            t.HasCheckConstraint("CK_deletion_log_reason_code", "reason_code IS NULL OR reason_code IN ('user_request','cancelled','support_request')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
