// <auto-generated />
using System;
using Balsm.Sessions.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balsm.Sessions.Infrastructure.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(SessionsDbContext))]
    partial class SessionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Balsm.Sessions.Domain.Entities.ActiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("device_label");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("device_type");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RefreshTokenId")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("active_session", "public", t =>
                        {
                            t.HasCheckConstraint("CK_active_session_device_type", "device_type IN ('phone','tablet','desktop','web')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
