using Balsm.Supervisor.Services;
using Microsoft.AspNetCore.Http;

namespace Balsm.Supervisor.Middleware;

/// <summary>
/// Validates X-Balsm-Local-Token on loopback requests.
/// If the token matches the one generated by LocalCliTokenService,
/// the request is marked as locally authenticated (bypasses session cookie check).
/// Only honoured for loopback source addresses (127.0.0.1 / ::1).
/// </summary>
public sealed class LocalOsTrustMiddleware(RequestDelegate next)
{
    internal const string HeaderName = "X-Balsm-Local-Token";
    internal const string LocalClaimKey = "LocalCli";

    public async Task InvokeAsync(HttpContext context)
    {
        var token = LocalCliTokenService.CurrentToken;
        if (token is not null && IsLoopback(context) &&
            context.Request.Headers.TryGetValue(HeaderName, out var header) &&
            string.Equals(header.ToString(), token, StringComparison.Ordinal))
        {
            context.Items[LocalClaimKey] = true;
        }

        await next(context);
    }

    private static bool IsLoopback(HttpContext context)
    {
        var addr = context.Connection.RemoteIpAddress;
        return addr is not null && System.Net.IPAddress.IsLoopback(addr);
    }
}
